name: Node.js CI
on: [push, pull_request]
jobs:
  server:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.16.3]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: yarn install
      run: yarn install
    - name: yarn lint
      run: yarn lint
    - name: yarn typecheck
      run: yarn typecheck
    - name: yarn build
      run: yarn build
  client:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.16.3]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: yarn install
      working-directory: ./client
      run: yarn install
    - name: yarn test
      working-directory: ./client
      run: yarn test
    - name: yarn lint
      working-directory: ./client
      run: yarn lint
    - name: yarn typecheck
      working-directory: ./client
      run: yarn typecheck
    - name: yarn build
      working-directory: ./client
      run: yarn build